core:
  - all:
      - changed-files:
          - any-glob-to-any-file: "lua/breeze/**"
          - all-globs-to-all-files:
              - "!lua/breeze/groups/**"
              - "!lua/breeze/colors/**"

groups:
  - changed-files:
      - any-glob-to-any-file: "lua/breeze/groups/**"

base:
  - changed-files:
      - any-glob-to-any-file:
          - "lua/breeze/groups/base.lua"
          - "lua/breeze/groups/kinds.lua"
          - "lua/breeze/groups/treesitter.lua"
          - "lua/breeze/groups/semantic_tokens.lua"

colors:
  - changed-files:
      - any-glob-to-any-file: "lua/breeze/colors/**"
